# Generated by Django 5.2.7 on 2026-04-13 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2)),
                ('documento', models.CharField(max_length=20)),
                ('nome_razao', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('contrato_social', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('referencia', models.TextField()),
                ('plano', models.CharField(max_length=100)),
                ('fidelidade', models.BooleanField(default=True)),
                ('vencimento', models.CharField(max_length=2)),
                ('vencimento_id', models.CharField(blank=True, max_length=10, null=True)),
                ('opcional', models.BooleanField(default=False)),
                ('pagamento_instalacao', models.CharField(max_length=50)),
                ('data_instalacao', models.DateField()),
                ('periodo_instalacao', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10)),
                ('origem', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
            },
        ),
    ]
