# Generated by Django 5.2.7 on 2026-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando Confirmação'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
