# Generated by Django 5.2.7 on 2026-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cadastro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
