# Generated by Django 5.2.7 on 2026-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cadastro_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_documento_frente',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_documento_verso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='levar_termo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='selfie_documento',
            field=models.FileField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
