# Generated by Django 5.2.7 on 2026-04-16 12:23

import cadastros.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cadastro_comprovante_residencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models.path_comprovante),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='contrato_social',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models.path_contrato),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='documento',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='foto_documento_frente',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models.path_doc_frente),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='foto_documento_verso',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models.path_doc_verso),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='selfie_documento',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models.path_selfie),
        ),
        migrations.CreateModel(
            name='HistoricalCadastro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2)),
                ('documento', models.CharField(db_index=True, max_length=20)),
                ('nome_razao', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('contrato_social', models.TextField(blank=True, max_length=100, null=True)),
                ('comprovante_residencia', models.TextField(blank=True, max_length=100, null=True)),
                ('foto_documento_frente', models.TextField(blank=True, max_length=100, null=True)),
                ('foto_documento_verso', models.TextField(blank=True, max_length=100, null=True)),
                ('selfie_documento', models.TextField(blank=True, max_length=100, null=True)),
                ('levar_termo', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('referencia', models.TextField()),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('plano', models.CharField(max_length=100)),
                ('fidelidade', models.BooleanField(default=True)),
                ('vencimento', models.CharField(max_length=2)),
                ('vencimento_id', models.CharField(blank=True, max_length=10, null=True)),
                ('opcional', models.BooleanField(default=False)),
                ('pagamento_instalacao', models.CharField(max_length=50)),
                ('data_instalacao', models.DateField()),
                ('periodo_instalacao', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10)),
                ('origem', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando Confirmação'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cadastro',
                'verbose_name_plural': 'historical Cadastros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
