# Generated by Django 5.2.7 on 2026-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cadastro_comprovante_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='ficha_manual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='ficha_manual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
