# Generated by Django 5.2.7 on 2026-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_cadastro_ficha_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
