# Generated by Django 6.0.4 on 2026-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_cadastro_uf_historicalcadastro_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='ixc_lead_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='ixc_lead_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='ixc_lead_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='ixc_lead_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
