# Generated by Django 6.0.4 on 2026-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_cadastro_ixc_lead_enviado_em_cadastro_ixc_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
