# Generated by Django 6.0.5 on 2026-05-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_cadastro_complemento_cadastro_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfigOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antecedencia_minima_instalacao', models.PositiveSmallIntegerField(default=1, help_text='1 = mínimo amanhã; 2 = depois de amanhã, etc.')),
                ('texto_ajuda_documentos', models.TextField(blank=True, help_text='Texto opcional exibido no passo de documentos (futuro front).')),
                ('modelo_observacoes_ficha', models.TextField(blank=True, help_text='Bloco extra acrescentado ao final da ficha automática (consultores).')),
                ('exigir_fotos_documentacao', models.BooleanField(default=True, help_text='Padrão quando a cidade não define override.')),
            ],
            options={
                'verbose_name': 'Configuração geral da ficha',
                'verbose_name_plural': 'Configuração geral da ficha',
            },
        ),
        migrations.CreateModel(
            name='CidadeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome_exibicao', models.CharField(max_length=120)),
                ('uf_padrao', models.CharField(max_length=2)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('skip_etapa_documentacao', models.BooleanField(default=False, help_text='Se verdadeiro, o passo de upload de documentos é pulado.')),
                ('permite_opcao_termo', models.BooleanField(default=False, help_text='Exibe “levar termo” em vez de comprovante (Unamar/Cabo Frio/SP).')),
                ('sempre_exibir_pagamento_instalacao', models.BooleanField(default=False, help_text='Maricá: sempre mostrar forma de pagamento da instalação.')),
                ('instalacao_com_fidelidade_gratis', models.BooleanField(default=True, help_text='Se falso, usa valores abaixo mesmo com fidelidade.')),
                ('instalacao_valor_com_fidel_reais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instalacao_valor_sem_fidel_reais', models.DecimalField(decimal_places=2, default=360, max_digits=10)),
                ('ixc_filial_id', models.CharField(blank=True, max_length=32)),
                ('ixc_cidade_id', models.CharField(blank=True, max_length=32)),
                ('exigir_fotos_documentacao', models.BooleanField(blank=True, help_text='Vazio = usar configuração global da ficha.', null=True)),
            ],
            options={
                'verbose_name': 'Cidade / filial (ficha)',
                'verbose_name_plural': 'Cidades / filiais (ficha)',
                'ordering': ['ordem', 'nome_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(help_text='Nome interno para o admin', max_length=120)),
            ],
            options={
                'verbose_name': 'Grupo de planos',
                'verbose_name_plural': 'Grupos de planos',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FaixaVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.PositiveSmallIntegerField()),
                ('dia_fim', models.PositiveSmallIntegerField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_vencimento', to='cadastros.cidadeoperacao')),
            ],
            options={
                'verbose_name': 'Faixa de vencimento',
                'verbose_name_plural': 'Faixas de vencimento',
                'ordering': ['cidade', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_str', models.CharField(help_text="Dois dígitos, ex.: '03'", max_length=2)),
                ('ixc_id', models.CharField(help_text='ID de vencimento no IXC (ou texto para referência)', max_length=32)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cadastros.faixavencimento')),
            ],
            options={
                'verbose_name': 'Opção de vencimento',
                'verbose_name_plural': 'Opções de vencimento',
                'ordering': ['faixa', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='cidadeoperacao',
            name='grupo_planos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='cadastros.planogrupo'),
        ),
        migrations.CreateModel(
            name='VagaInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10)),
                ('vagas_max', models.PositiveIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vaga de instalação',
                'verbose_name_plural': 'Vagas de instalação',
                'ordering': ['data', 'periodo'],
                'unique_together': {('data', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PlanoDefinicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Valor enviado no campo plano (ex.: essencial, 1giga, plano_300)')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_html', models.TextField(help_text='HTML permitido (quebras &lt;br&gt;)')),
                ('texto_opcional', models.TextField(blank=True, help_text='Se preenchido, exibe opção extra (roteador/mesh) para este plano')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ixc_plano_venda_id', models.CharField(blank=True, help_text='ID do plano de venda no IXC (sobrescreve o mapa padrão se preenchido)', max_length=32)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='cadastros.planogrupo')),
            ],
            options={
                'verbose_name': 'Definição de plano',
                'verbose_name_plural': 'Definições de planos',
                'ordering': ['grupo', 'ordem', 'codigo'],
                'unique_together': {('grupo', 'codigo')},
            },
        ),
    ]
