# Generated by Django 6.0.5 on 2026-05-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_plano_texto_opcional_repetidor_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodefinicao',
            name='texto_opcional',
            field=models.TextField(blank=True, help_text='Texto do opcional «repetidor Mesh em aluguel». Se vazio, usa o padrão global da ficha.'),
        ),
    ]
