# Generated by Django 6.0.4 on 2026-05-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_cadastro_documento_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='anonimizado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o cadastro foi anonimizado por exigência LGPD.', null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='consentimento_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP de onde o consentimento foi registrado.', null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, help_text='Cliente declarou ter lido e concordado com a Política de Privacidade.'),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='anonimizado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o cadastro foi anonimizado por exigência LGPD.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='consentimento_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP de onde o consentimento foi registrado.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, help_text='Cliente declarou ter lido e concordado com a Política de Privacidade.'),
        ),
        migrations.CreateModel(
            name='AcessoDadoSensivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('visualizou', 'Visualizou cadastro'), ('exportou', 'Exportou JSON'), ('editou', 'Editou cadastro'), ('anonimizado', 'Anonimizou cadastro')], default='visualizou', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='cadastros.cadastro')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_pii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a dado sensível',
                'verbose_name_plural': 'Acessos a dados sensíveis',
                'ordering': ['-criado_em'],
            },
        ),
    ]
