# Generated by Django 6.0.5 on 2026-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_cadastro_ixc_envio_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='ixc_envio_logs',
            field=models.JSONField(blank=True, default=dict, help_text='Auditoria do envio IXC; ex.: {"text": "…linhas de log…"}. No PG pode vir como jsonb legado.'),
        ),
        migrations.AlterField(
            model_name='historicalcadastro',
            name='ixc_envio_logs',
            field=models.JSONField(blank=True, default=dict, help_text='Auditoria do envio IXC; ex.: {"text": "…linhas de log…"}. No PG pode vir como jsonb legado.'),
        ),
    ]
