# Generated by Django 6.0.5 on 2026-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_alter_cadastro_ixc_envio_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origemcanalvenda',
            name='ixc_id',
            field=models.CharField(help_text='ID no IXC: preferir o da tela CRM > Cadastros > Canal de vendas (combo «Canal de venda» no lead). Se usar só Origens, pode não preencher o canal.', max_length=32),
        ),
    ]
