# Generated by Django 6.0.5 on 2026-05-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_cadastro_ixc_prospect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcadastro',
            name='ixc_prospect_id',
            field=models.CharField(blank=True, help_text='ID do registro crm_prospect (prospecção) no IXC, quando criado pelo envio da ficha.', max_length=50, null=True),
        ),
    ]
