# Generated by Django 6.0.5 on 2026-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_cadastro_ixc_candidato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcadastro',
            name='ixc_candidato_id',
            field=models.CharField(blank=True, help_text='ID do registro crm_candidatos no IXC, quando criado encadeado após o lead.', max_length=50, null=True),
        ),
    ]
