# Generated by Django 6.0.5 on 2026-05-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_cadastro_ixc_contrato_id'),
        ('cadastros', '0037_remove_cadastro_ixc_radusuario_id'),
    ]

    operations = [
    ]
