# Generated by Django 6.0.5 on 2026-05-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_merge_20260512_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='ixc_candidato_id',
        ),
        migrations.RemoveField(
            model_name='historicalcadastro',
            name='ixc_candidato_id',
        ),
    ]
