# Generated by Django 6.0.4 on 2026-05-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_alter_historicalcadastro_ixc_candidato_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorIXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do vendedor (exibido no painel; não vai para o IXC).', max_length=120)),
                ('ixc_id', models.CharField(help_text='ID do funcionário / vendedor no IXC (ex.: 242). Usado em id_vendedor / id_responsavel / id_vendedor_ativ.', max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Opcional: contato interno (não enviado ao IXC).', max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Opcional: contato interno (não enviado ao IXC).', max_length=40)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True, help_text='Vendedores inativos não aparecem no select de novos cadastros.')),
                ('padrao', models.BooleanField(default=False, help_text='Pré-selecionado em cadastros novos quando o admin não escolher um explicitamente.')),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Vendedor / responsável IXC',
                'verbose_name_plural': 'Vendedores / responsáveis IXC',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ixc_prospect_id',
            field=models.CharField(blank=True, help_text='ID retornado pelo IXC na etapa 2 (prospecção CRM: em geral `crm_canditados` / `crm_candidatos`; fallback legado `crm_prospect`). Usado também em fluxos de contrato quando o IXC espera esse vínculo.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcadastro',
            name='ixc_prospect_id',
            field=models.CharField(blank=True, help_text='ID retornado pelo IXC na etapa 2 (prospecção CRM: em geral `crm_canditados` / `crm_candidatos`; fallback legado `crm_prospect`). Usado também em fluxos de contrato quando o IXC espera esse vínculo.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='vendedor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Vendedor / responsável vinculado a este cadastro. O `ixc_id` do vendedor é enviado ao IXC como id_vendedor / id_responsavel / id_vendedor_ativ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros', to='cadastros.vendedorixc'),
        ),
        migrations.AddField(
            model_name='historicalcadastro',
            name='vendedor_responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vendedor / responsável vinculado a este cadastro. O `ixc_id` do vendedor é enviado ao IXC como id_vendedor / id_responsavel / id_vendedor_ativ.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.vendedorixc'),
        ),
    ]
