# Generated by Django 6.0.4 on 2026-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_vendedor_ixc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfigoperacao',
            name='ixc_fidelidade_meses',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantidade de meses para o campo `fidelidade` do contrato quando o cliente aceita fidelidade.'),
        ),
        migrations.AddField(
            model_name='appconfigoperacao',
            name='ixc_produto_instalacao_id',
            field=models.CharField(blank=True, default='146', help_text='id_produto_ativ enviado quando o cliente paga taxa de instalação (padrão 146 = R$ 100,00).', max_length=32),
        ),
        migrations.AddField(
            model_name='appconfigoperacao',
            name='ixc_tipo_documento_fatura_id',
            field=models.CharField(blank=True, default='501', help_text='id_tipo_documento da fatura mensal (padrão 501).', max_length=32),
        ),
        migrations.AddField(
            model_name='cidadeoperacao',
            name='ixc_carteira_cobranca_id',
            field=models.CharField(blank=True, help_text='ID da carteira de cobrança no IXC (id_carteira_cobranca, padrão «COM DESCONTO»).', max_length=32),
        ),
        migrations.AddField(
            model_name='cidadeoperacao',
            name='ixc_setor_id',
            field=models.CharField(blank=True, help_text='ID do setor no IXC (id_setor). Vazio usa o default por filial.', max_length=32),
        ),
        migrations.AddField(
            model_name='cidadeoperacao',
            name='ixc_tipo_doc_ativ_id',
            field=models.CharField(blank=True, help_text='ID do tipo de documento opcional/ativação (id_tipo_doc_ativ). Vazio usa o default por filial.', max_length=32),
        ),
    ]
