# Generated by Django 6.0.4 on 2026-05-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_seed_ids_ixc_producao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorixc',
            name='ixc_id_responsavel',
            field=models.CharField(blank=True, help_text='ID do responsável pela conta no IXC (id_responsavel). Vazio = usa o mesmo ID do vendedor.', max_length=32),
        ),
        migrations.AddField(
            model_name='vendedorixc',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Consultor (usuário do sistema) vinculado a este vendedor IXC. Quando preenchido, os cadastros criados por esse consultor herdam automaticamente seus IDs no payload IXC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_ixc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedorixc',
            name='ixc_id',
            field=models.CharField(help_text='ID do funcionário / vendedor no IXC (ex.: 242). Vai para id_vendedor e id_vendedor_ativ.', max_length=32, unique=True),
        ),
    ]
