# Generated by Django 6.0.4 on 2026-05-14 15:30

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_vendedor_consultor_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='comprovante_residencia',
            field=models.FileField(blank=True, null=True, storage=cadastros.models._doc_storage, upload_to=cadastros.models.path_comprovante),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='contrato_social',
            field=models.FileField(blank=True, null=True, storage=cadastros.models._doc_storage, upload_to=cadastros.models.path_contrato),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='foto_documento_frente',
            field=models.FileField(blank=True, null=True, storage=cadastros.models._doc_storage, upload_to=cadastros.models.path_doc_frente),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='foto_documento_verso',
            field=models.FileField(blank=True, null=True, storage=cadastros.models._doc_storage, upload_to=cadastros.models.path_doc_verso),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='selfie_documento',
            field=models.FileField(blank=True, null=True, storage=cadastros.models._doc_storage, upload_to=cadastros.models.path_selfie),
        ),
    ]
