"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import json
import os
from decouple import config
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Em produção defina explicitamente DEBUG=False no .env (localmente o padrão é True).
DEBUG = config('DEBUG', default=True, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-altere-em-producao'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY é obrigatória quando DEBUG=False. Defina no arquivo .env.'
        )

# Função para limpar ALLOWED_HOSTS caso o usuário cole a URL completa
def parse_allowed_hosts(v):
    if v is None or not str(v).strip():
        return []
    hosts = [s.strip() for s in str(v).split(',')]
    clean_hosts = []
    for host in hosts:
        if not host:
            continue
        # Remove https:// ou http://
        host = host.replace('https://', '').replace('http://', '')
        # Remove barras finais
        host = host.split('/')[0].strip()
        if host:
            clean_hosts.append(host)
    return clean_hosts

# Liste domínios/IP separados por vírgula. Em desenvolvimento, se omitido ou vazio → localhost.
_allowed_raw = config('ALLOWED_HOSTS', default='').strip()
if not _allowed_raw:
    _allowed_raw = 'localhost,127.0.0.1' if DEBUG else ''
ALLOWED_HOSTS = parse_allowed_hosts(_allowed_raw)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS não pode estar vazio com DEBUG=False. Defina no .env (ex.: seu-dominio.com.br).'
    )

# Se estiver na Vercel e não tiver DATABASE_URL, o SQLite vai dar erro de escrita.
# Use o Vercel Postgres para produção!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'cadastros',
    'crispy_forms',
    'crispy_bootstrap5',
    'simple_history',
]

# Cloudinary: só ative em produção preenchendo CLOUDINARY_CLOUD_NAME (e chaves). Sem isso, uploads usam disco local (MEDIA_ROOT).
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='').strip()
if CLOUDINARY_CLOUD_NAME:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': config('CLOUDINARY_API_KEY', default='').strip(),
        'API_SECRET': config('CLOUDINARY_API_SECRET', default='').strip(),
    }


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    try:
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except Exception:
        # Fallback to SQLite if DATABASE_URL is malformed
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise storage to compress and cache static files
STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if CLOUDINARY_CLOUD_NAME
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Allow WhiteNoise to serve files even when DEBUG is True
WHITENOISE_USE_FINDERS = DEBUG

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# HTTPS / proxy reverso (Render, Railway, nginx, etc.)
_csrf_raw = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_raw.split(',') if x.strip()]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    _hsts = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    if _hsts > 0:
        SECURE_HSTS_SECONDS = _hsts
        SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)

# IXC API Config
# ------------------------------------------------------------------------------
# IDs e defaults abaixo com valor preenchido no código ou no .env são, em regra,
# APENAS PARA TESTE / homologação (documentação Postman, demo IXC). Na operação real
# cada cidade terá filial, carteira, planos (vd), tipo de documento, canal de venda,
# etc., conforme o seu IXC — hoje parte disso já pode ser modelada em Operação
# (CidadeOperacao, PlanoDefinicao, OrigemCanalVenda); o restante será substituído
# quando os IDs definitivos forem definidos por ambiente (.env) ou evolução do painel.
# ------------------------------------------------------------------------------
IXC_API_URL = config('IXC_API_URL', default='')
IXC_API_TOKEN = config('IXC_API_TOKEN', default='')
IXC_LEAD_RESOURCE = config('IXC_LEAD_RESOURCE', default='')
# True = se o WS de ``contato`` falhar, tenta crm_leads / crm_sp_leads / crm_lead (senão etapa 1 é só contato).
IXC_LEAD_AFTER_CONTATO_TRY_CRM = config('IXC_LEAD_AFTER_CONTATO_TRY_CRM', default=False, cast=bool)
# True (padrão) = etapa 1 usa só o WS ``contato``; nunca cai em crm_leads (evita pipeline comercial/venda/login variável no IXC).
# False = permite o fallback acima (IXC_LEAD_AFTER_CONTATO_TRY_CRM) quando não houver IXC_LEAD_RESOURCE fixo.
IXC_LEAD_CONTATO_ONLY = config('IXC_LEAD_CONTATO_ONLY', default=True, cast=bool)
# Override de EMERGÊNCIA (homologação) — força um id de plano de venda / canal
# para todos os cadastros do ambiente. Em produção use o painel Operação.
IXC_FORCE_PLANO_VENDA_ID = config('IXC_FORCE_PLANO_VENDA_ID', default='').strip()
IXC_FORCE_CANAL_VENDA_ID = config('IXC_FORCE_CANAL_VENDA_ID', default='').strip()
# Canal de venda default quando o slug da origem ainda não está em OrigemCanalVenda.
IXC_DEFAULT_CANAL_VENDA_ID = config('IXC_DEFAULT_CANAL_VENDA_ID', default='').strip()
# Campanha (input#id_campanha no CRM IXC): só envie se o seu webservice exigir; costuma ser cadastro diferente de «Canal de venda».
IXC_FORCE_CAMPANHA_ID = config('IXC_FORCE_CAMPANHA_ID', default='').strip()
IXC_DEFAULT_CAMPANHA_ID = config('IXC_DEFAULT_CAMPANHA_ID', default='').strip()
IXC_SEND_CANAL_AS_ID_CAMPANHA = config('IXC_SEND_CANAL_AS_ID_CAMPANHA', default=False, cast=bool)
# True = após incluir, chama alterar com o mesmo JSON (2ª requisição). Pode duplicar lead em alguns IXC — use só se necessário.
IXC_LEAD_POST_ALTERAR = config('IXC_LEAD_POST_ALTERAR', default=False, cast=bool)
# True = se já houver ixc_lead_id no cadastro, não chama o webservice de lead de novo. False = sempre tenta criar lead.
IXC_REUSE_LOCAL_LEAD_ID = config('IXC_REUSE_LOCAL_LEAD_ID', default=False, cast=bool)
# Etapa 2 no painel usa force=True (ignora esta flag). Só afeta chamadas programáticas sem force.
IXC_CREATE_CRM_PROSPECT = config('IXC_CREATE_CRM_PROSPECT', default=False, cast=bool)
# Vazio = tenta `crm_canditados`, `crm_candidatos`, depois `crm_prospect` e IXC_CRM_PROSPECT_FALLBACK_RESOURCES.
IXC_CRM_PROSPECT_RESOURCE = config('IXC_CRM_PROSPECT_RESOURCE', default='').strip()
# Opcional: nomes extras de recurso WS para prospect, na ordem, separados por vírgula (conforme Postman do provedor).
IXC_CRM_PROSPECT_FALLBACK_RESOURCES = config('IXC_CRM_PROSPECT_FALLBACK_RESOURCES', default='').strip()
# Após lead com sucesso, POST em crm_candidatos (vínculo id_contato / id_lead). False = só lead.
IXC_CHAIN_CRM_CANDIDATOS_AFTER_LEAD = config('IXC_CHAIN_CRM_CANDIDATOS_AFTER_LEAD', default=True, cast=bool)
# Recurso WS candidatos (opcional). Vazio = tenta `crm_candidatos` + IXC_CRM_CANDIDATOS_FALLBACK_RESOURCES.
IXC_CRM_CANDIDATOS_RESOURCE = config('IXC_CRM_CANDIDATOS_RESOURCE', default='').strip()
IXC_CRM_CANDIDATOS_FALLBACK_RESOURCES = config('IXC_CRM_CANDIDATOS_FALLBACK_RESOURCES', default='').strip()
IXC_CREATE_CRM_CANDIDATOS = config('IXC_CREATE_CRM_CANDIDATOS', default=True, cast=bool)
# FK ``cidade`` obrigatória no ``crm_canditados`` (Postman). Se o slug não tiver ``ixc_cidade_id`` na Operação, use este ID.
IXC_CRM_CANDIDATOS_CIDADE_FALLBACK = config('IXC_CRM_CANDIDATOS_CIDADE_FALLBACK', default='1').strip()
# FKs de negócio do contrato (filial, carteira, vendedor, plano, tipo doc, etc.)
# saíram daqui: agora vêm do painel /admin-dash/operacao/ com defaults documentados
# em `cadastros/ixc_ids.py` (FILIAIS / SETORES / PLANOS / CARTEIRAS / VENCIMENTOS).

# --- WS cliente_arquivos — upload multipart de SELFIE/RG/comprovante ao cliente IXC
# Nome do recurso (varia por instalação? padrão IXC Provedor é `cliente_arquivos`).
IXC_ARQUIVOS_RESOURCE = config('IXC_ARQUIVOS_RESOURCE', default='cliente_arquivos').strip()

# --- Teste WS cliente_contrato — painel superusuário
IXC_CLIENTE_CONTRATO_RESOURCE = config('IXC_CLIENTE_CONTRATO_RESOURCE', default='cliente_contrato').strip()
# Opcional: após criar o contrato, POST em ``/webservice/v1/<recurso>`` com JSON ``{"id_contrato": "<id>"}`` para «aguardando assinatura» (número varia por instalação IXC, ex.: cliente_contrato_23529).
# Número do recurso varia por instalação IXC; vazio = não chama o 2º POST (aguardando assinatura).
IXC_CLIENTE_CONTRATO_ASSINATURA_RESOURCE = config(
    'IXC_CLIENTE_CONTRATO_ASSINATURA_RESOURCE', default='cliente_contrato_23529'
).strip()
IXC_CLIENTE_CONTRATO_ASSINATURA_JSON_KEY = config(
    'IXC_CLIENTE_CONTRATO_ASSINATURA_JSON_KEY', default='id_contrato'
).strip()
# Se vazio, não envia cabeçalho ``ixcsoft`` neste POST (como no Postman do provedor). Preencha se o IXC exigir.
IXC_CLIENTE_CONTRATO_ASSINATURA_IXCSOFT = config(
    'IXC_CLIENTE_CONTRATO_ASSINATURA_IXCSOFT', default=''
).strip()
IXC_CONTRATO_TEST_ID_CLIENTE = config('IXC_CONTRATO_TEST_ID_CLIENTE', default='').strip()
# Fallback só quando a ficha **não** tem ``ixc_prospect_id`` / ``ixc_lead_id`` (homolog sem envio IXC). Com vínculo na ficha, o contrato usa sempre esse ID — não o valor fixo do .env.
IXC_CONTRATO_TEST_ID_CONTRATO = config('IXC_CONTRATO_TEST_ID_CONTRATO', default='').strip()
# IDs antigos `IXC_CONTRATO_TEST_ID_*` (vd_contrato, filial, tipo_contrato,
# tipo_documento, carteira, tipo_doc_ativ, descrição) saíram daqui — agora o
# sistema busca em `/admin-dash/operacao/` com defaults em
# `cadastros/ixc_ids.py`.
#
# Letra do tipo do contrato (I/S/…): fallback se listar vd_contrato não trouxer ``tipo``;
# deve coincidir com o plano de venda no IXC.
IXC_CONTRATO_TEST_TIPO = config('IXC_CONTRATO_TEST_TIPO', default='I').strip()
# True (padrão): listar vd_contrato e usar o ``tipo`` do plano no POST (evita erro IXC tipo≠plano).
IXC_CONTRATO_TEST_TIPO_SINCR_COM_PLANO = config(
    'IXC_CONTRATO_TEST_TIPO_SINCR_COM_PLANO', default=True, cast=bool
)
IXC_CONTRATO_TEST_ID_TIPO_CONTRATO = config('IXC_CONTRATO_TEST_ID_TIPO_CONTRATO', default='10').strip()
IXC_CONTRATO_TEST_ID_MODELO = config('IXC_CONTRATO_TEST_ID_MODELO', default='1').strip()
# Vendedor default (legado) só usado quando não há `VendedorIXC` ativo
# vinculado ao cadastro. O fluxo padrão é cadastrar em /admin-dash/operacao/vendedores/.
IXC_CONTRATO_TEST_ID_VENDEDOR = config('IXC_CONTRATO_TEST_ID_VENDEDOR', default='1').strip()
# Comissão (opcional) — sobrescreve o template se preenchido.
IXC_CONTRATO_TEST_COMISSAO = config('IXC_CONTRATO_TEST_COMISSAO', default='').strip()
# Texto do campo «Descrição» do contrato no IXC (sobrescreve plano da ficha do portal se preenchido).
IXC_CONTRATO_TEST_CONTRATO_DESCRICAO = config('IXC_CONTRATO_TEST_CONTRATO_DESCRICAO', default='').strip()
# Doc oficial IXC Provedor: letra (ex.: P); algumas bases usam ID numérico — sobrescreva no .env se necessário.
IXC_CONTRATO_TEST_TIPO_COBRANCA_ID = config('IXC_CONTRATO_TEST_TIPO_COBRANCA_ID', default='P').strip()
IXC_CONTRATO_TEST_CC_PREVISAO = config('IXC_CONTRATO_TEST_CC_PREVISAO', default='M').strip()
IXC_CONTRATO_TEST_RENOVACAO_AUTOMATICA = config('IXC_CONTRATO_TEST_RENOVACAO_AUTOMATICA', default='S').strip()
IXC_CONTRATO_TEST_BASE_GERACAO_TIPO_DOC = config('IXC_CONTRATO_TEST_BASE_GERACAO_TIPO_DOC', default='P').strip()
IXC_CONTRATO_TEST_BLOQUEIO_AUTOMATICO = config('IXC_CONTRATO_TEST_BLOQUEIO_AUTOMATICO', default='S').strip()
IXC_CONTRATO_TEST_AVISO_ATRASO = config('IXC_CONTRATO_TEST_AVISO_ATRASO', default='S').strip()
IXC_CONTRATO_TEST_ENDERECO_PADRAO_CLIENTE = config(
    'IXC_CONTRATO_TEST_ENDERECO_PADRAO_CLIENTE', default='S'
).strip()
# No mesmo POST ``incluir``: marcar contrato para fluxo de assinatura (tela IXC «Status»).
IXC_CONTRATO_AGUARDANDO_ASSINATURA_INCLUIR = config(
    'IXC_CONTRATO_AGUARDANDO_ASSINATURA_INCLUIR', default=True, cast=bool
)
IXC_CONTRATO_TEST_ASSINATURA_DIGITAL = config(
    'IXC_CONTRATO_TEST_ASSINATURA_DIGITAL', default='S'
).strip()
IXC_CONTRATO_TEST_INTEGRACAO_ASSINATURA_DIGITAL = config(
    'IXC_CONTRATO_TEST_INTEGRACAO_ASSINATURA_DIGITAL', default=''
).strip()
IXC_CONTRATO_TEST_GERAR_FINAN_ASSIN_DIGITAL = config(
    'IXC_CONTRATO_TEST_GERAR_FINAN_ASSIN_DIGITAL', default=''
).strip()
# Código de status no IXC (varia por instalação). Vazio = não envia ``status`` no incluir.
IXC_CONTRATO_TEST_STATUS = config('IXC_CONTRATO_TEST_STATUS', default='').strip()
# Recurso WS para listar plano de venda (sincroniza ``tipo``/FKs no POST ``cliente_contrato``).
IXC_VD_CONTRATO_RESOURCE = config('IXC_VD_CONTRATO_RESOURCE', default='vd_contrato').strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
    },
}

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'
